export default [
  {
    id: 0,
    gameCover:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/345820/library_600x900_2x.jpg?t=1572910710',
    gameHeader: '',
    gameDeveloper: '',
    gameClassification: '',
    gamePrice: 'R$ 36,99',
    gameName: "Shantae and the Pirate's Curse",
    gameLabel: 'Indie Game',
    gameCategories: [{ name: '' }, { name: '' }, { name: '' }],
  },
  {
    id: 1,
    gameCover:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/692850/library_600x900_2x.jpg?t=1669134724',
    gameHeader: '',
    gameDeveloper: '',
    gameClassification: '',
    gamePrice: 'R$ 75,49',
    gameName: 'Bloodstained: Ritual of the Night',
    gameLabel: 'From Castlevania Creator',
    gameCategories: [{ name: '' }, { name: '' }, { name: '' }],
  },
  {
    id: 2,
    gameCover:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/586140/library_600x900_2x.jpg?t=1638944011',
    gameHeader: '',
    gameDeveloper: '',
    gameClassification: '',
    gamePrice: 'R$ 72,99',
    gameName: 'BlazBlue: CentralFiction',
    gameLabel: 'Netcode Support',
    gameCategories: [{ name: '' }, { name: '' }, { name: '' }],
  },
  {
    id: 3,
    gameCover:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/1065180/library_600x900_2x.jpg?t=1667371981',
    gameHeader: '',
    gameDeveloper: '',
    gameClassification: '',
    gamePrice: 'R$ 37,99',
    gameName: 'Azure Striker Gunvolt 2',
    gameLabel: 'Indie Game',
    gameCategories: [{ name: '' }, { name: '' }, { name: '' }],
  },
  {
    id: 4,
    gameCover:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/999020/library_600x900_2x.jpg?t=1565074375',
    gameHeader: '',
    gameDeveloper: '',
    gameClassification: '',
    gamePrice: 'R$ 99,90',
    gameName: 'Megaman Zero/ZX Legacy Collection',
    gameLabel: 'Collection',
    gameCategories: [{ name: '' }, { name: '' }, { name: '' }],
  },
  {
    id: 5,
    gameCover:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/1451940/library_600x900_2x.jpg?t=1689126165',
    gameHeader: '',
    gameDeveloper: '',
    gameClassification: '',
    gamePrice: 'R$ 30,99',
    gameName: 'Neddy Streamer Overload',
    gameLabel: 'Indie Game',
    gameCategories: [{ name: '' }, { name: '' }, { name: '' }],
  },
  {
    id: 6,
    gameCover:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/377860/library_600x900_2x.jpg?t=1560844966',
    gameHeader: '',
    gameDeveloper: '',
    gameClassification: '',
    gamePrice: 'R$ 59,99',
    gameName: 'Mushihimesama',
    gameLabel: 'Arcade',
    gameCategories: [{ name: '' }, { name: '' }, { name: '' }],
  },
  {
    id: 7,
    gameCover:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/851100/library_600x900_2x.jpg?t=1671415207',
    gameHeader: '',
    gameDeveloper: '',
    gameClassification: '',
    gamePrice: 'R$ 34,99',
    gameName: 'Touhou: Luna Nights',
    gameLabel: 'Indie Game',
    gameCategories: [{ name: '' }, { name: '' }, { name: '' }],
  },
];
